### ISSUE TITLE
pymanopt.manifolds cannot import name 'HermitianPositiveDefinite'

### ISSUE THREAD

**Issue by sqzhen** [antoinecollas/robust_metric_learning#1]
from pymanopt.manifolds import (HermitianPositiveDefinite,SpecialHermitianPositiveDefinite)

ImportError: cannot import name 'HermitianPositiveDefinite'

**Comment by antoinecollas** [comment]
Hello,

There is a file called `install.sh` that you should follow to install this repository.
The pymanopt you have to install is the one from [https://github.com/antoinecollas/pymanopt](https://github.com/antoinecollas/pymanopt) .

**Comment by sqzhen** [comment]
xiexie，Thank you very much！！
